# -*- coding: utf-8 -*-
"""Caixa eletrônico

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrBfaoieA_hiJo8YnDJb21e-FeF-CjbJ
"""

# Este problema foi utilizado em 1723 Dojo(s).

# Desenvolva um programa que simule a entrega de notas quando um cliente efetuar um saque em um caixa eletrônico. Os requisitos básicos são os seguintes:

# Entregar o menor número de notas;
# É possível sacar o valor solicitado com as notas disponíveis;
# Saldo do cliente infinito;
# Quantidade de notas infinito (pode-se colocar um valor finito de cédulas para aumentar a dificuldade do problema);
# Notas disponíveis de R$ 100,00; R$ 50,00; R$ 20,00 e R$ 10,00
# Exemplos:

# Valor do Saque: R$ 30,00 – Resultado Esperado: Entregar 1 nota de R$20,00 e 1 nota de R$ 10,00.
# Valor do Saque: R$ 80,00 – Resultado Esperado: Entregar 1 nota de R$50,00 1 nota de R$ 20,00 e 1 nota de R$ 10,00.

# importando bibliotecas
from math import floor

# Notas disponíveis de R$ 100,00; R$ 50,00; R$ 20,00 e R$ 10,00
# D=d*q+r  qtd_cedulas=(D-r)/d e o dinheiro que sobrar será o resto r = D-d*q
n=float(input())

qtd_cel_100=floor(n/100)

resto_50=n-100*qtd_cel_100

qtd_cel_50=floor(resto_50/50)

resto_20=resto_50-50*qtd_cel_50

qtd_cel_20=floor(resto_20/20)

resto_10=resto_20-20*qtd_cel_20

qtd_cel_10=floor(resto_10/10)

print(f"Entregar {qtd_cel_100} nota de R$100,00,{qtd_cel_50} nota de R$50,00, {qtd_cel_20} nota de R$ 20,00 e {qtd_cel_10} nota de R$ 10,00.")