# -*- coding: utf-8 -*-
"""FizzBuzz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gV7Rp1aLjUsLKvvxUMqefGpueUVL1yrr
"""

# FizzBuzz
# Neste problema, você deverá exibir uma lista de 1 a 100, um em cada linha, com as seguintes exceções:

# Números divisíveis por 3 deve aparecer como 'Fizz' ao invés do número;
# Números divisíveis por 5 devem aparecer como 'Buzz' ao invés do número;
# Números divisíveis por 3 e 5 devem aparecer como 'FizzBuzz' ao invés do número'.
def fizzBuzz(n):
  if n % 3 == 0 and n % 5 != 0:
    print("Fizz")
  if n % 3 != 0 and n % 5 == 0:
    print("Buzz")
  if n % 3 == 0 and n % 5 == 0:
    print("FizzBuzz")
  if n % 3 != 0 and n % 5 != 0:
    print(n)

c=0
while c<100:
  c+=1
  fizzBuzz(c)