# -*- coding: utf-8 -*-
"""Jokenpo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BnSlAUjtFPE8mjocZb-d4LcQCI7_zfVV
"""

# Jokenpo é uma brincadeira japonesa, onde dois jogadores escolhem um dentre três possíveis itens: Pedra, Papel ou Tesoura.

# O objetivo é fazer um juiz de Jokenpo que dada a jogada dos dois jogadores informa o resultado da partida.

# As regras são as seguintes:

# Pedra empata com Pedra e ganha de Tesoura
# Tesoura empata com Tesoura e ganha de Papel
# Papel empata com Papel e ganha de Pedra

from random import randint as ri

# Jokenpo é uma brincadeira japonesa, onde dois jogadores escolhem um dentre três possíveis itens:
# [1] Pedra
# [2] Papel
# [3] Tesoura
usuario = int(input("""Jokenpo é uma brincadeira japonesa, onde dois jogadores escolhem um dentre três possíveis itens:
[1] Pedra
[2] Papel
[3] Tesoura
Escolha sua jogada: """))
pc=ri(1,3)
if pc== usuario:
  print("Empate") 
if pc == 1 and usuario == 2:
  print("Você escolheu Papel")
  print("Computador escolheu pedra")
  print("Vocẽ venceu")
if pc == 1 and usuario == 3:
  print("Você escolheu Tesoura")
  print("Computador escolheu pedra")
  print("Vocẽ perdeu")
if pc == 2 and usuario == 1:
  print("Você escolheu pedra")
  print("Computador escolheu papel")
  print("Vocẽ perdeu")
if pc == 2 and usuario == 3:
  print("Você escolheu Tesoura")
  print("Computador escolheu papel")
  print("Vocẽ venceu") 
if pc == 3 and usuario == 1:
  print("Você escolheu pedra")
  print("Computador escolheu tesoura")
  print("Vocẽ venceu")
if pc == 3 and usuario == 2:
  print("Você escolheu Papel")
  print("Computador escolheu tesoura") 
  print("Vocẽ perdeu")